config/routes.rb
Rails.application.routes.draw do
  # get 'about/page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'about', to: 'about#page'
  resources :articles 
  get 'signup', to:"users#new"
  resources :users , except: [:new]
  # post 'users', to: 'users#create'
    # , only: [:new, :show, :index, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: {minimum: 3, maximmum: 50}
    validates :description, presence: true, length: {minimum: 5, maximmum: 1000}
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    has_many :articles
    validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 5, maximum:100}, format: {with: VALID_EMAIL_REGEX}

    has_secure_password
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def page
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    def show 
        
    end

    def index
        @articles=Article.all
    end
    def new
        @article=Article.new
    end

    def edit
        
    end

    def create
        @article= Article.new(article_params)
        # render plain: @article.inspect
        @article.user=User.first
        if @article.save 
            flash[:notice]="Article successfully created "
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end


    def update 
        
        if @article.update(article_params)
            flash[:notice]="Article successfully updated "
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end

    def destroy 
        
        @article.destroy
        redirect_to articles_path
    end
    
    
    private

    def set_article
        @article= Article.find(params[:id])
    end
    def article_params
        params.require(:article).permit(:title, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user=User.new
    end
    def create 
        @user =User.new(user_params)
        if @user.save
            flash[:notice] = "Welcome to the blog"
            redirect_to articles_path
        else
            render 'new'
        end

    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/page.html.erb
<div class="div">
    This is the about page of the blogs app.
</div>

<%= link_to 'Articles listing', articles_path %> |

<%= link_to 'Home page', root_path %>

app/views/articles/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">

            <%= render 'shared/errors', obj: @article %>
    <%= form_with(model: @article, class:" shadow p-3 mb-5 bg-info rounded", local: true) do |f| %>

    <div class="form-group row d-flex">
        <%= f.label :title, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of the article" %>
        </div>
    </div>
    <br>
    <div class="form-group row d-flex">
        <%= f.label :description, class: "col-2 col-form-label text-light" %> 
        <div class="col-10">
            <%= f.text_area :description,rows: 10,   class: "form-control shadow rounded", placeholder: "Description of the article" %>
        </div>
    </div>
    <br>

    <div class="form-group d-flex justify-content-center">
        <%= f.submit class:"btn btn-outline-light btn-lg d-flex justify-content-center" %>
    </div>
    <% end %>
    </div>
    <%= link_to 'Return to articles listing', articles_path, class: "d-flex justify-content-center text-info" %>
    </div>
</div>

app/views/articles/edit.html.erb
<div id="page-content">
    <h1 class="text-center mt-4"> Update article</h1>


<%= render 'form' %>



</div>

app/views/articles/index.html.erb
<div id="page-content">
<h1 class="text-center mt-4"> Article listing</h1>

<div class="container">
<% @articles.each do |ar| %>
<div class="row justify-content-md-center">
    <div class="col-8 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
        By <%= ar.user.username if ar.user%>
        </div>
        <div class="card-body">
        <h5 class="card-title"><%= link_to ar.title, article_path(ar), class: "text-success" %></h5>
        <p class="card-text"><%= truncate(ar.description, length: 50) %></p>

        <%= link_to 'View', article_path(ar), class:"btn btn-outline-success" %>
        <%= link_to 'Edit', edit_article_path(ar), class: "btn btn-outline-info" %>
        <%= link_to 'Delete', article_path(ar), method: :delete, data: { confirm:"Are you sure?"} , class: "btn btn-outline-danger" %>
    </div>

        <div class="card-footer text-muted">
        <small>Created ago <%= time_ago_in_words(ar.created_at) %>,
            edited ago <%= time_ago_in_words(ar.updated_at) %> </small>
        </div>
    </div>
</div>
</div>
<% end %> 
</div>
<p>
    <%= link_to "Create new article", new_article_path %>
</p>

</div>

app/views/articles/new.html.erb
<div id="page-content">
<h1 class="text-center mt-4"> Create new article</h1>


<%= render 'form' %>



</div>

app/views/articles/show.html.erb
<div id="page-content">
    <h2 class="text-center mt-4"><%= @article.title %> </h2>
    
    <div class="container">
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
            by <%= @article.user.username if @article.user %>
            </div>
            <div class="card-body">
            <p class="card-text"><%= simple_format(@article.description) %></p>
            <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm:"Are you sure?"} , class: "btn btn-outline-danger" %>
        </div>
    
            <div class="card-footer text-muted">
            <small>Created ago <%= time_ago_in_words(@article.created_at) %>,
                edited ago <%= time_ago_in_words(@article.updated_at) %> </small>
            </div>
        </div>
    </div>
    </div>

    </div>
    <p>
        <%= link_to "Create new article", new_article_path %>
    </p>
    
    </div>

app/views/home/index.html.erb
<div id="page-content">
<div class="container" id="home-container">
    <div class="jumbotron text-center text-white">
    <h1 class="display-4">Veersa Blog</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to "Sign up", signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div>
</div>




  <!-- <%= link_to 'Articles listing', articles_path %>

|

<%= link_to 'About page', about_path %> -->

app/views/layouts/_messages.html.erb
<div class="container">
<% flash.each do |name,msg| %>
<div class="alert alert-success d-flex align-items-center alert-dismissible fade show" role="alert">
    <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
    <div>
        <%= msg %>
    </div>
  
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light text-light">
  <div class="container-fluid">
    <%= link_to "Veersa", root_path, class: "navbar-brand text-light", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link active" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "New Article", new_article_path, class: "dropdown-item" %></li>
            <li><%= link_to "Show all", articles_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  <body>

    <%= render 'layouts/nav' %>
    <div id="page-content">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
    <footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
      <div class="container text-center">
        <small>Copyright &copy; Veersatech</small>
      </div>
    </footer>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>

<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from beign saved saved</h4>
    <ul>
        <% obj.errors.full_messages.each do |msg| %>
        <li> <%= msg %></li>
        <% end %>
        </ul>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div> 
    
<% end %>

app/views/users/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">

            <%= render 'shared/errors', obj: @user %>
    <%= form_with(model: @user, class:" shadow p-3 mb-5 bg-info rounded", local: true) do |f| %>

    <div class="form-group row d-flex">
        <%= f.label :username, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter your username" %>
        </div>
    </div>
    <br>
    <div class="form-group row d-flex">
        <%= f.label :email, class: "col-2 col-form-label text-light" %> 
        <div class="col-10">
            <%= f.email_field :email,   class: "form-control shadow rounded", placeholder: "Enter your email address" %>
        </div>
    </div>
    <br>
    <div class="form-group row d-flex">
        <%= f.label :password, class: "col-2 col-form-label text-light" %> 
        <div class="col-10">
            <%= f.password_field :password,   class: "form-control shadow rounded", placeholder: "Choose a password" %>
        </div>
    </div>
    <br>

    <div class="form-group d-flex justify-content-center">
        <%= f.submit "Sign up", class:"btn btn-outline-light btn-lg d-flex justify-content-center" %>
    </div>
    <% end %>
    </div>
    <%= link_to 'Return to articles listing', articles_path, class: "d-flex justify-content-center text-info" %>
    </div>
</div>

app/views/users/new.html.erb
<div id="page-content">
    <h1 class="text-center mt-4"> Sign up</h1>    
    <%= render 'form' %>
    </div>